### ISSUE TITLE
[Bug]:   Can't see the hotspot on the explorer via web browser

### ISSUE THREAD

**Issue by rami202** [helium/explorer#680] opened 2021-08-29 20:56 UTC
### What happened?

A bug happened! i have added a Sensecap M1 hotspot to the helium network and it has been up and running for a week now. However i only can see the hotspot on the helium app but not on the explorer. In addition, it is possible to locate this hotspot on the explorer by clicking on the nearby hotspots near my hotspot then it becomes visible so could you maybe have a look at this bug and fix it? see my picture for the reference.

<img width="914" alt="Screenshot 2021-08-29 at 22 52 27" src="https://user-images.githubusercontent.com/45793317/131265058-50918a26-3ebb-4d48-b9b0-76f3ac272a5e.png">

### URL

https://explorer.helium.com/hotspots/11A6grXXWTzwpAUT1KKPB6d8D15FKE4biDNeT1jW64dejV4U1kt

### What browsers are you seeing the problem on?

Chrome, Safari

### Do you see the issue on Mobile or Desktop?

Desktop

### Relevant log output

```shell
See the attached picture
```

**Comment by ArnoutVerbeken** [comment] 2021-08-29 21:44
Duplicate of https://github.com/helium/explorer/issues/672

**Closed as completed** 2021-08-30 02:14 UTC
Labels: bug
