### ISSUE TITLE
Add Witness count in new Explorer

### ISSUE THREAD

**Issue by Topius** [helium/explorer#474] opened 2021-06-11 16:11 UTC
**Describe the bug**
In Old Explorer there is Total witness count when you go to a Gateway statistics.

In New Explorer when you get to Gateway statistics there is a list of Witnesses without a Number (so needs manually scrolling and counting)  Please Add Witness count in Witness details of Gateway.

**To Reproduce**
1. Go to 'https://explorer-beta.helium.com/hotspots'
2. Click on 'Any gateway with Witness'
3. Go to 'Witness information'
4. There is no total number of witnesses like in old explorer

**Expected behavior**
There should be count like in old Explorer

**Screenshots**
2 1x Old 1x New
![Old Witness Counted](https://user-images.githubusercontent.com/34198115/121716424-0ed98e80-caf1-11eb-913a-04f34eae8887.JPG)
![New explorer Witness Not Counted](https://user-images.githubusercontent.com/34198115/121716429-10a35200-caf1-11eb-8ae1-6cdd31c584e7.JPG)

**Desktop (please complete the following information):**
ON all Desktops

**Smartphone (please complete the following information):**
 -On all IOS

**Additional context**

**Comment by cokes518** [comment] 2021-06-23 16:40
dupe of #457

**Closed by cokes518** 2021-06-23 16:40 UTC
