### ISSUE TITLE
[Bug]: Explorer hotspot maker onboarded numbers are stale

### ISSUE THREAD

**Issue by killtheplanet** [helium/explorer#651] opened 2021-08-16 21:43 UTC
### What happened?

The counter on the makers tab seems to have got stuck and has not incremented in some time, despite hotspots being added.

### URL

https://explorer.helium.com/hotspots
And
https://explorer-v1.helium.com/hotspots

### What browsers are you seeing the problem on?

Chrome, Safari, Brave, Firefox, Opera, Microsoft Edge

### Do you see the issue on Mobile or Desktop?

Mobile, Desktop

### Relevant log output

Related to #622 which appears closed.

When comparing v2 numbers at https://explorer.helium.com/hotspots of 'hotspots added' the numbers are stale, yet total count of hotspots are increasing.

The data appears to be from 13 August 2021, where:
```
Helium Inc: 1025
Cal-Chip: 52554
Nebra Ltd: 5735
SyncroB.it: 2178
Bobcat: 39839
LongAP: 467
etc.
```

Numbers are slightly worse at https://explorer-v1.helium.com/hotspots where the numbers appear to date from 18th July, where:
```
Helium Inc: 975
Cal-Chip: 43774
Nebra Ltd: 2369
SyncroB.it: 1138
Bobcat: 25386
LongAP: 319
etc.
```

**Comment by shawaj** [comment] 2021-08-16 21:59
Think https://etl.dewi.org/public/dashboard/5f3cd0b4-9317-48a3-88f0-aae5adf80aed is more up to date

**Comment by cokes518** [comment] 2021-09-01 16:30
looks like a dupe of #622 which is now fixed

**Closed as completed by cokes518** 2021-09-01 16:30 UTC
Labels: bug
