### ISSUE TITLE
Checklist not updated although some of them are completed

### ISSUE THREAD

**Issue by KiDU911** [helium/explorer#398] opened 2021-05-26 11:28 UTC
Withess a challenge not checked although is in present in activity list.
Also the earnings is very low and different in last week.
My rak v2 miner.
https://explorer.helium.com/hotspots/11A42Tq5PpmB1vP74wW5tp7QtedRsMgG3krEvhngpeBi43bQxsU
Thanks.

**Comment by cokes518** [comment] 2021-06-09 19:35
looks like a valid issue @danielcolinjames can you take a look?

**Comment by cokes518** [comment] 2021-08-18 17:19
this should be fixed. root cause is that we weren't looking for older transaction type.

**Closed by cokes518** 2021-08-18 17:19 UTC
