### ISSUE TITLE
Checklist missing last 2 points although they are completed

### ISSUE THREAD

**Issue by TheTrunto** [helium/explorer#397] opened 2021-05-26 11:03 UTC
<img width="1440" alt="Bildschirmfoto 2021-05-26 um 13 02 03" src="https://user-images.githubusercontent.com/84846798/119649275-bcc31880-be22-11eb-8ee4-641fbdc03653.png">
<img width="1440" alt="Bildschirmfoto 2021-05-26 um 13 02 17" src="https://user-images.githubusercontent.com/84846798/119649283-bf257280-be22-11eb-9140-4d5fc8c65e2c.png">

**Comment by TheTrunto** [comment] 2021-05-26 11:04
Hello everyone

So, on my rak v2 I have the following issue(s):
My checklist still says I did not complete the last 2 tasks on my miner....but it did :)
Witness a Challenge and Transfer Data.

I heard/read this affects my miner/earnings? but that is another thing.

When I check in the app it says the same like in the explorer, when I click on another miner and come back to mine  - it says I completed the whole checklist (only in the app).

Every time I just click on my miner (explorer or app) it still says missing the last 2 points.

My miner did complete the whole checklist, just recently (under activity, last point) he did the witness.

Why is this happening and why does it show my checklist as not completed although it does or did all the tasks?

Funny Yellow Mantis
https://explorer.helium.com/hotspots/1122ggPwHLfmwxNNkU1VXoRqJMHPGFUxC3UakHnxtgNVMRNy5Xbu

I also have phases where my miners does not do anything for like hours....and suddenly does something again...then again hours nothing.....but that all started after these updates....

**Comment by cokes518** [comment] 2021-06-09 19:36
same as #398

**Comment by TheTrunto** [comment] 2021-06-09 20:03
> same as #398

and in the beta version he same issue...jus that there is only the last point missing.....

**Comment by cokes518** [comment] 2021-08-18 17:19
this should be fixed. root cause is that we weren't looking for older transaction type.

**Closed by cokes518** 2021-08-18 17:19 UTC
